/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.19).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package counter.api;

import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import counter.model.Flight;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2020-04-16T22:58:40.224Z[GMT]")
@Api(value = "flights", description = "the flights API")
public interface FlightsApi {

    Logger log = LoggerFactory.getLogger(FlightsApi.class);

    // default Optional<ObjectMapper> getObjectMapper() {
    //     return Optional.empty();
    // }

    // default Optional<HttpServletRequest> getRequest() {
    //     return Optional.empty();
    // }

    // default Optional<String> getAcceptHeader() {
    //     return getRequest().map(r -> r.getHeader("Accept"));
    // }

    @ApiOperation(value = "Get all flights", nickname = "flightsGet", notes = "", response = Flight.class, responseContainer = "List", tags = {
            "Flight", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "Successfully got the list of flights", response = Flight.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "Invalid Request", response = String.class) })
    @RequestMapping(value = "/flights", produces = { "application/json", "text/plain" }, method = RequestMethod.GET)
    default ResponseEntity<List<Flight>> flightsGet() {
        // if (getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
        //     if (getAcceptHeader().get().contains("application/json")) {
        //         try {
        //             return new ResponseEntity<>(getObjectMapper().get().readValue("", List.class),
        //                     HttpStatus.NOT_IMPLEMENTED);
        //         } catch (IOException e) {
        //             log.error("Couldn't serialize response for content type application/json", e);
        //             return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
        //         }
        //     }
        // } else {
        //     log.warn(
        //             "ObjectMapper or HttpServletRequest not configured in default FlightsApi interface so no example is generated");
        // }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

}
